// Racer and stage definitions for CRUIS'N BEANS.
// Stages are POINT-TO-POINT roads described as segments:
//   { len, bend (total heading change in radians, + bends right),
//     dh (elevation change), zone }

export const RACERS = [
  {
    id: 'andy',
    name: 'ANDY',
    car: 'RED STALLION 5.0',
    tagline: 'SMOOTH OPERATOR',
    portrait: 'assets/img/andy-portrait.png',
    carSprite: 'assets/img/andy-car.png',
    rearSprite: 'assets/img/sm/andy-car-rear.png',
    frontSprite: 'assets/img/sm/andy-car.png',
    spriteWidth: 5.4,
    stats: { speed: 0.9, grip: 0.75, wheelie: 0.8 },
    topSpeed: 64,
    accel: 23,
    steer: 1.0,
    aiSkill: 0.93,
  },
  {
    id: 'adam',
    name: 'ADAM',
    car: 'SILENT THREE',
    tagline: 'ZERO EMISSIONS* (*EXCEPT BEANS)',
    portrait: 'assets/img/adam-portrait.png',
    carSprite: 'assets/img/adam-car.png',
    rearSprite: 'assets/img/sm/adam-car-rear.png',
    frontSprite: 'assets/img/sm/adam-car.png',
    spriteWidth: 5.4,
    stats: { speed: 0.8, grip: 0.9, wheelie: 0.7 },
    topSpeed: 62,
    accel: 27,
    steer: 1.12,
    aiSkill: 0.91,
  },
  {
    id: 'lance',
    name: 'LANCE',
    car: 'DESERT DREAMER VAN',
    tagline: 'WORLD\u2019S GREATEST GRANDPA',
    portrait: 'assets/img/lance-portrait.png',
    carSprite: 'assets/img/lance-car.png',
    rearSprite: 'assets/img/sm/lance-car-rear.png',
    frontSprite: 'assets/img/sm/lance-car.png',
    spriteWidth: 6.0,
    stats: { speed: 0.7, grip: 0.65, wheelie: 1.0 },
    topSpeed: 60,
    accel: 19,
    steer: 0.88,
    aiSkill: 0.89,
  },
  {
    id: 'elon',
    name: 'ELON',
    car: 'CHROME ROADSTER',
    tagline: 'TO THE MOON (VIA HIGHWAY)',
    portrait: 'assets/img/elon-portrait.png',
    carSprite: 'assets/img/elon-car.png',
    rearSprite: 'assets/img/sm/elon-car-rear.png',
    frontSprite: 'assets/img/sm/elon-car.png',
    spriteWidth: 5.2,
    stats: { speed: 1.0, grip: 0.7, wheelie: 0.6 },
    topSpeed: 66,
    accel: 25,
    steer: 0.95,
    aiSkill: 0.95,
  },
];

// Generic cabinet rivals filling out the pack (canvas-drawn sprites).
export const RIVALS = [
  { id: 'rival1', name: 'BIG SAL', car: 'MEATBALL EXPRESS', color: '#d9612c', topSpeed: 60, accel: 20, aiSkill: 0.88, spriteWidth: 5.4 },
  { id: 'rival2', name: 'TINA T.', car: 'PINK LIGHTNING', color: '#e654a8', topSpeed: 63, accel: 24, aiSkill: 0.92, spriteWidth: 5.2 },
  { id: 'rival3', name: 'HOT ROD HAL', car: 'THE FLAMER', color: '#3a7fd9', topSpeed: 62, accel: 22, aiSkill: 0.9, spriteWidth: 5.3 },
];

export const STAGES = [
  {
    id: 'hawaii',
    name: 'HAWAII COAST',
    blurb: 'OCEAN HIGHWAY \u2022 VOLCANO \u2022 BIG AIR',
    sky: ['#4faaff', '#9fdcff', '#ffe9b8'],
    ground: '#3fa24d',
    groundDetail: '#2f8a3e',
    shoulder: '#e7d089',
    fogColor: '#cfeaff',
    startTime: 48,
    checkpointEvery: 1250,
    checkpointBonus: 24,
    segments: [
      { len: 500, bend: 0, dh: 0, zone: 'beachtown' },
      { len: 900, bend: -0.5, dh: 0, zone: 'coast' },
      { len: 700, bend: 0, dh: 0, zone: 'coast' },
      { len: 800, bend: 0.7, dh: 0, zone: 'coast' },
      { len: 600, bend: -0.6, dh: 2, zone: 'palms' },
      { len: 700, bend: 0, dh: 0, zone: 'palms' },
      { len: 900, bend: 1.35, dh: 12, zone: 'cliff' },
      { len: 700, bend: 1.35, dh: 4, zone: 'cliff' },
      { len: 800, bend: 0, dh: -4, zone: 'lava' },
      { len: 700, bend: -0.5, dh: 0, zone: 'lava' },
      { len: 900, bend: 0.4, dh: -10, zone: 'palms' },
      { len: 700, bend: 0, dh: -4, zone: 'beachtown' },
    ],
    zones: {
      beachtown: { props: ['palm', 'hibiscus', 'sign_lei', 'sign_beans', 'building_surf'], density: 1.4 },
      coast: { props: ['palm', 'palm', 'hibiscus', 'sign_cruise'], density: 1.0, ocean: 'right' },
      palms: { props: ['palm', 'palm', 'palm', 'rock', 'sign_beans'], density: 1.8 },
      cliff: { props: ['rock', 'rock', 'palm', 'sign_falling'], density: 1.2 },
      lava: { props: ['lavarock', 'lavarock', 'palm', 'sign_hot'], density: 1.3 },
    },
    landmarks: [
      { kind: 'volcano', at: 0.72, x: -420, w: 900, h: 380 },
      { kind: 'cruiseShip', at: 0.28, x: 200, w: 260, h: 80 },
      { kind: 'cruiseShip', at: 0.06, x: 260, w: 220, h: 70 },
    ],
    shortcut: { enter: 0.545, exit: 0.665, side: 1, label: 'JUNGLE CUT' },
    ramps: [0.18, 0.46, 0.84],
    beans: [0.1, 0.3, 0.52, 0.7, 0.9],
    animals: [
      { kind: 'seagull', count: 5 },
      { kind: 'pig', count: 4 },
    ],
    traffic: { oncoming: 9, same: 4 },
  },
  {
    id: 'desert',
    name: 'DESERT HIGHWAY',
    blurb: 'US-66 TO THE MESAS \u2022 COWS \u2022 SHIMMER',
    sky: ['#ff9a3d', '#ffcf6b', '#ffe9c2'],
    ground: '#d9a05a',
    groundDetail: '#c08a48',
    shoulder: '#b97f42',
    fogColor: '#ffd9a0',
    startTime: 49,
    checkpointEvery: 1300,
    checkpointBonus: 25,
    segments: [
      { len: 700, bend: 0, dh: 0, zone: 'flats' },
      { len: 1000, bend: 0.3, dh: 0, zone: 'flats' },
      { len: 900, bend: 0, dh: 2, zone: 'cactus' },
      { len: 1100, bend: -1.05, dh: 6, zone: 'canyon' },
      { len: 800, bend: -1.05, dh: -2, zone: 'canyon' },
      { len: 900, bend: 0.2, dh: -4, zone: 'cactus' },
      { len: 1000, bend: 0.4, dh: 0, zone: 'flats' },
      { len: 1000, bend: 0, dh: 2, zone: 'mesa' },
      { len: 1000, bend: -0.3, dh: 2, zone: 'mesa' },
      { len: 1000, bend: 0, dh: 0, zone: 'mesa' },
    ],
    zones: {
      flats: { props: ['cactus', 'rock', 'skull', 'sign_gas', 'sign_beans'], density: 0.9 },
      cactus: { props: ['cactus', 'cactus', 'cactus', 'rock', 'sign_van'], density: 1.6 },
      canyon: { props: ['rock', 'rock', 'rock', 'skull'], density: 1.5 },
      mesa: { props: ['cactus', 'rock', 'sign_diner'], density: 0.9 },
    },
    landmarks: [
      { kind: 'mesaBig', at: 0.98, x: -260, w: 700, h: 260 },
      { kind: 'mesaBig', at: 0.92, x: 300, w: 600, h: 220 },
      { kind: 'mesaBig', at: 0.8, x: -350, w: 500, h: 200 },
      { kind: 'dinerSign', at: 0.35, x: 30, w: 26, h: 40 },
    ],
    shortcut: { enter: 0.28, exit: 0.42, side: -1, label: 'DRY RIVERBED' },
    ramps: [0.22, 0.5, 0.78],
    beans: [0.12, 0.33, 0.55, 0.75, 0.93],
    animals: [
      { kind: 'cow', count: 6 },
      { kind: 'armadillo', count: 4 },
    ],
    traffic: { oncoming: 10, same: 4 },
    shimmer: true,
  },
  {
    id: 'tequila',
    name: 'TEQUILA TOWN',
    blurb: 'DRIVE THRU TOWN \u2022 PICADO \u2022 NEON CANTINA',
    sky: ['#2b1a5e', '#7c3fa0', '#ff9d5c'],
    ground: '#a86f3d',
    groundDetail: '#8f5c30',
    shoulder: '#c9985f',
    fogColor: '#b878c9',
    startTime: 47,
    checkpointEvery: 1200,
    checkpointBonus: 24,
    segments: [
      { len: 600, bend: 0, dh: 0, zone: 'agave' },
      { len: 900, bend: 0.6, dh: 2, zone: 'agave' },
      { len: 800, bend: -0.5, dh: 0, zone: 'vineyard' },
      { len: 600, bend: 0, dh: 0, zone: 'gate' },
      { len: 900, bend: 0.4, dh: 0, zone: 'town' },
      { len: 700, bend: -0.7, dh: 0, zone: 'town' },
      { len: 600, bend: 0, dh: 0, zone: 'plaza' },
      { len: 900, bend: 1.3, dh: 8, zone: 'hills' },
      { len: 700, bend: 1.2, dh: -8, zone: 'hills' },
      { len: 800, bend: -0.4, dh: 0, zone: 'agave' },
      { len: 700, bend: 0, dh: 0, zone: 'cantina' },
    ],
    zones: {
      agave: { props: ['agave', 'agave', 'cactus', 'sign_beans'], density: 1.4 },
      vineyard: { props: ['agave', 'agave', 'agave', 'sign_tequila'], density: 2.0 },
      gate: { props: ['building', 'lantern', 'agave'], density: 1.2 },
      town: { props: ['building', 'building', 'building', 'lantern'], density: 2.6, street: true, picado: true },
      plaza: { props: ['building', 'lantern', 'building'], density: 2.0, street: true, picado: true },
      hills: { props: ['rock', 'agave', 'cactus'], density: 1.3 },
      cantina: { props: ['building', 'lantern', 'sign_cantina'], density: 1.8, street: true },
    },
    landmarks: [
      { kind: 'townGate', at: 0.395, x: 0, w: 44, h: 22 },
      { kind: 'church', at: 0.56, x: 60, w: 120, h: 110 },
      { kind: 'fountain', at: 0.63, x: -22, w: 22, h: 14 },
      { kind: 'cantinaNeon', at: 0.985, x: 26, w: 60, h: 46 },
    ],
    shortcut: { enter: 0.685, exit: 0.83, side: 1, label: 'ALLEY CUT' },
    ramps: [0.3, 0.75],
    beans: [0.14, 0.36, 0.58, 0.8],
    animals: [
      { kind: 'donkey', count: 5 },
      { kind: 'chicken', count: 4 },
    ],
    traffic: { oncoming: 8, same: 4 },
  },
];
